GestionConsommationVehiculeMvc/Models/consommation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConsommationVehiculeMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consommation
    {
        public int Id { get; set; }
        public int IdVehicule { get; set; }
        public int IdTypeConsommation { get; set; }
        public double quantite { get; set; }
        public int PrixUnitaire { get; set; }
        public double PrixTotal { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public System.DateTime DateConsommation { get; set; }
        public string NumeroDocument { get; set; }
        public Nullable<bool> Expirable { get; set; }
    
        public virtual typeconsommation typeconsommation { get; set; }
        public virtual vehicule vehicule { get; set; }
    }
}

GestionConsommationVehiculeMvc/Controllers/ConsommationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestionConsommationVehiculeMvc.Models;

namespace GestionConsommationVehiculeMvc.Controllers
{
    public class ConsommationController : Controller
    {
        private GestionConsommationVehiculeEntities12 db = new GestionConsommationVehiculeEntities12();
        //
        // GET: /Consommation/
        public ActionResult Index3()
        {
            ViewBag.msg = TempData["msg"] as string;
            var consommations = db.consommations.Include(c => c.typeconsommation).Include(c => c.vehicule);
            return View(consommations.ToList());
        }

        public ActionResult Index( )
        {
            ViewBag.msg = TempData["msg"] as string;
            var consommations = db.consommations.Include(c => c.typeconsommation).Include(c => c.vehicule);
            return View(consommations.ToList());
        }
         [HttpPost]
        public ActionResult Index(DateTime? datedebut,DateTime?datefin)
        {
            ViewBag.Rapports = "Rapport detaille du:" + datedebut +  "Au"   + datefin;
            var consommations = db.consommations.Where(c => c.DateConsommation >= datedebut && c.DateConsommation <= datefin).ToList();
            return View(consommations);
        }
         public ActionResult Index4()
         {
             ViewBag.msg = TempData["msg"] as string;
             var consommations = db.consommations.Include(c => c.typeconsommation).Include(c => c.vehicule);
             return View(consommations.ToList());
         }
         [HttpPost]
         public ActionResult Index4(DateTime? datedebut, DateTime? datefin)
         {
             ViewBag.Rapport = "Rapport detaille du:" + datedebut + "Au" + datefin;
             var consommations = db.consommations.Where(c => c.DateConsommation >= datedebut && c.DateConsommation <= datefin).ToList();
             return View(consommations);
         }
        public ActionResult Index1()
        {
            List<ConsommationModele> model = (from K in db.consommations
                                              join Ve in db.vehicules on K.IdVehicule equals Ve.Id 
                                              select new { K.IdVehicule, Ve.NumeroImatriculation, K.PrixTotal,K.DateConsommation } into x
                                              group x by new { x.DateConsommation } into g
                                              select new ConsommationModele
                                              {
                                                 
                                                  DateConsommation = (g.Key.DateConsommation),
                                                  prixtotal = (g.Select(x => x.PrixTotal).Sum()),
                                                  //factura = (g.Select(x => x.facturationID).Count()),
                                              }).ToList();
            return View(model);
        }
        public ActionResult Index5()
        {
            ViewBag.msg = TempData["msg"] as string;
            List<ConsommationModele> model = (from K in db.consommations
                                              join Ve in db.vehicules on K.IdVehicule equals Ve.Id
                                              select new { K.IdVehicule, Ve.NumeroImatriculation, K.PrixTotal, K.DateConsommation } into x
                                              group x by new { x.DateConsommation } into g
                                              select new ConsommationModele
                                              {
                                                  DateConsommation = (g.Key.DateConsommation),
                                                  prixtotal =(g.Select(x => x.PrixTotal).Sum()),
                                                  //factura = (g.Select(x => x.facturationID).Count()),
                                              }).ToList();
            return View(model);
        }
       
        public ActionResult  Index2()
        {
            List<ConsommationModele> model = (from K in db.consommations
                                              join Ve in db.vehicules on K.IdVehicule equals Ve.Id
                                              select new { K.IdVehicule, Ve.NumeroImatriculation, K.PrixTotal } into x
                                              group x by new { x.NumeroImatriculation } into g
                                              select new ConsommationModele
                                              {
                                                  plaque = (g.Key.NumeroImatriculation),
                                                  prixtotal = (g.Select(x => x.PrixTotal).Sum()),
                                                  //factura = (g.Select(x => x.facturationID).Count()),
                                              }).ToList();
            return View(model);
        }

        //
        // GET: /Consommation/Details/5

        public ActionResult Details(int id = 0)
        {
            consommation consommation = db.consommations.Find(id);
            if (consommation == null)
            {
                return HttpNotFound();
            }
            return View(consommation);
        }

        //
        // GET: /Consommation/Create

        public ActionResult Create()
        {
            TempData["msg"] ="Insertion faite avec Succes dans consommation";
            ViewBag.IdTypeConsommation = new SelectList(db.typeconsommations, "Id", "NomTypeConsommation");
            ViewBag.IdVehicule = new SelectList(db.vehicules, "Id", "NumeroImatriculation");
            return View();
        }

        //
        // POST: /Consommation/Create

        [HttpPost]
        public ActionResult Create(consommation consommation)
        {
            if (ModelState.IsValid)
            {
                db.consommations.Add(consommation);
                db.SaveChanges();
                return RedirectToAction("Index3");
            }

            ViewBag.IdTypeConsommation = new SelectList(db.typeconsommations, "Id", "NomTypeConsommation", consommation.IdTypeConsommation);
            ViewBag.IdVehicule = new SelectList(db.vehicules, "Id", "NumeroImatriculation", consommation.IdVehicule);
            return View(consommation);
        }

        //
        // GET: /Consommation/Edit/5

        public ActionResult Edit(int id = 0)
        {
            consommation consommation = db.consommations.Find(id);
            if (consommation == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdTypeConsommation = new SelectList(db.typeconsommations, "Id", "NomTypeConsommation", consommation.IdTypeConsommation);
            ViewBag.IdVehicule = new SelectList(db.vehicules, "Id", "NumeroImatriculation", consommation.IdVehicule);
            return View(consommation);
        }

        //
        // POST: /Consommation/Edit/5

        [HttpPost]
        public ActionResult Edit(consommation consommation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(consommation).State = EntityState.Modified;
                db.SaveChanges();
                TempData["msg"] = "Modification faite avec success";
                return RedirectToAction("Index3");
            }
            ViewBag.IdTypeConsommation = new SelectList(db.typeconsommations, "Id", "NomTypeConsommation", consommation.IdTypeConsommation);
            ViewBag.IdVehicule = new SelectList(db.vehicules, "Id", "NumeroImatriculation", consommation.IdVehicule);
            return View(consommation);
        }

        //
        // GET: /Consommation/Delete/5

        public ActionResult Delete(int id = 0)
        {
            consommation consommation = db.consommations.Find(id);
            if (consommation == null)
            {
                return HttpNotFound();
            }
            return View(consommation);
        }

        //
        // POST: /Consommation/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            consommation consommation = db.consommations.Find(id);
            db.consommations.Remove(consommation);
            db.SaveChanges();
            TempData["msg"] = "Suppression faite avec success";
            return RedirectToAction("Index3");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GestionConsommationVehiculeMvc/Views/Consommation/Create.cshtml
@model GestionConsommationVehiculeMvc.Models.consommation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layouts/_Default.cshtml";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="background-color: rgb(0, 255, 255)">
    <div class="fa fa-home" style="text-align: center; font-size: 50px">Administrateurs</div>


    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)

        <fieldset>
            @{
                
            var date = DateTime.Now;
            }
            <legend></legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.IdVehicule, "vehicule:")
            </div>
            <div class="col-md-6" style="font-size: 20px">
                @Html.DropDownList("IdVehicule", null, "selectionner Vehicule",
            htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdVehicule)
            </div>


            <div class="col-md-6" style="font-size: 20px">
                @Html.DropDownList("IdTypeConsommation", null, "selectionner consommation",
            htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTypeConsommation)
            </div>

            <div class="col-md-6" style="font-size: 20px">
                <label>PrixUnitaire:</label>
                <input type="number" name="PrixUnitaire" autocomplete="off" class="form-control" id="unit_price" />
            </div>

            <div class="col-md-6" style="font-size: 20px">
                <label>Quantite:</label>
                <input type="number" name="quantite" autocomplete="off" class="form-control" id="qty" />
            </div>
            <div class="col-md-6" style="font-size: 20px">
                <label>MontantPaye:</label>
                <input type="number" class="form-control" readonly="" id="total" name="PrixTotal" />
            </div>



            <div class="col-md-6" style="font-size: 20px">
                <label>DateDebut:</label>
                <input type="date" class="form-control" name="DateDebut" />
            </div>
            <div class="col-md-6" style="font-size: 20px">
                <label>DateFin:</label>
                <input type="date" class="form-control" name="DateFin" />
            </div>
            <div class="col-md-6" style="font-size: 20px">
                <label>NumeroDocument:</label>
                <input type="text" class="form-control" autocomplete="off" name="NumeroDocument" />
            </div>

            <div class="col-md-6" style="font-size: 20px">
                <label>DateConsommation:</label>
                <input value="@date"  class="form-control" readonly="" name="DateConsommation"/>
            </div>




            <div class="col-md-6" style="font-size: 20px">
                <label></label>
                <input type="submit" value="Enregistrer" class="form-control btn btn-warning" />
            </div>


            <div class="col-md-6" style="font-size: 20px">
                <label>Expirable</label>
                @Html.EditorFor(model => model.Expirable)
                @Html.ValidationMessageFor(model => model.Expirable)
            </div>
            <br />
        </fieldset>
    }

    <div style="font-size: 20px">
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

GestionConsommationVehiculeMvc/Views/Consommation/Delete.cshtml
@model GestionConsommationVehiculeMvc.Models.consommation

@{
    ViewBag.Title = "Delete";
Layout = "~/Views/Layouts/_Default.cshtml";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="background-color:rgb(255, 255, 255)">



<h5>Are you sure you want to delete this?</h5>
<fieldset>
    <legend></legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.vehicule.NumeroImatriculation)
    </div>
    <div class="display-field">

        @Html.DisplayFor(model => model.vehicule.NumeroImatriculation)

    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.typeconsommation.NomTypeConsommation)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.typeconsommation.NomTypeConsommation)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.quantite)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.quantite)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PrixUnitaire)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PrixUnitaire)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PrixTotal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PrixTotal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateDebut)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateDebut)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateFin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateFin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateConsommation)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateConsommation)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NumeroDocument)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumeroDocument)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Expirable)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Expirable)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p style="font-size:15px">
        <input type="submit" value="Delete" /> 
        @Html.ActionLink("Back to List", "Index3")
    </p>
}
</div>

GestionConsommationVehiculeMvc/Views/Consommation/Details.cshtml
@model GestionConsommationVehiculeMvc.Models.consommation

@{
    ViewBag.Title = "Details";
Layout = "~/Views/Layouts/_Default.cshtml";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="background-color:rgb(255, 255, 255)">

<h2></h2>

<fieldset>
    <legend></legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.vehicule.NumeroImatriculation)
    </div>
    <div class="display-field">

        @Html.DisplayFor(model => model.vehicule.NumeroImatriculation)
    </div>

    <div class="display-label">

         @Html.DisplayNameFor(model => model.typeconsommation.NomTypeConsommation)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.typeconsommation.NomTypeConsommation)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.quantite)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.quantite)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PrixUnitaire)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PrixUnitaire)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PrixTotal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PrixTotal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateDebut)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateDebut)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateFin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateFin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateConsommation)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateConsommation)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NumeroDocument)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumeroDocument)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Expirable)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Expirable)
    </div>
</fieldset>
<p style="font-size:15px">
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index3")
</p>
</div>

GestionConsommationVehiculeMvc/Views/Consommation/Edit.cshtml
@model GestionConsommationVehiculeMvc.Models.consommation

@{
    ViewBag.Title = "Edit";
Layout = "~/Views/Layouts/_Default.cshtml";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="background-color:rgb(255, 255, 255)">

<h2>Modification</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>


        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.IdVehicule, "vehicule")

        </div>
        <div class="editor-field">
            @Html.DropDownList("IdVehicule", String.Empty)
            @Html.ValidationMessageFor(model => model.IdVehicule)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdTypeConsommation, "typeconsommation")
        </div>
        <div class="editor-field">
            @Html.DropDownList("IdTypeConsommation", String.Empty)
            @Html.ValidationMessageFor(model => model.IdTypeConsommation)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.quantite)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.quantite)
            @Html.ValidationMessageFor(model => model.quantite)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PrixUnitaire)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PrixUnitaire)
            @Html.ValidationMessageFor(model => model.PrixUnitaire)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PrixTotal)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PrixTotal)
            @Html.ValidationMessageFor(model => model.PrixTotal)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateDebut)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateDebut)
            @Html.ValidationMessageFor(model => model.DateDebut)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateFin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateFin)
            @Html.ValidationMessageFor(model => model.DateFin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateConsommation)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateConsommation)
            @Html.ValidationMessageFor(model => model.DateConsommation)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NumeroDocument)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NumeroDocument)
            @Html.ValidationMessageFor(model => model.NumeroDocument)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Expirable)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Expirable)
            @Html.ValidationMessageFor(model => model.Expirable)
        </div><br/>

  <div style="font-size:30px">
         <p>
            <input type="submit" value="Save" class=" btn btn-success form-group col-md-2"/>
        </p>
        @Html.ActionLink("Back to List", "Index")

    </div>
    </fieldset>
}



</div>

GestionConsommationVehiculeMvc/Views/Consommation/Index.cshtml
@model IEnumerable<GestionConsommationVehiculeMvc.Models.consommation>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layouts/_Default.cshtml";
}
<!Doctype html>
<html lang="en">
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="background-color: rgb(0, 255, 255)">
        

    <h5  style="text-align: center; font-size:30px;background-color:rgb(255, 216, 0)"><u><B>Rapport Detaille des consommations des vehicules</B></u></h5><br/> 
    <b style=" font-size:27px;background-color:rgb(237, 17, 49)"><i class="fa fa-refresh fa-spin" ></i><b style="text-align:center ;color:black">@Html.ActionLink("Mettre a l'etat initial Cette affichage du rapport de la consommation des vehicules", "Index")</b></b>    
           
 <p>  
   @using (Html.BeginForm("Index", "Consommation", FormMethod.Post))
   {
       
       <span id="startDate"><b>DateDebut</b></span><input type="date" name="datedebut"/>
       
       
       <span id="endDate"><b>DateFin</b></span><input type="date" name="datefin"/>
       <input type="submit" name="submit" value="Rapport Detaille"/>
   }  
  </p>
  
        <h5  style="text-align: center; font-size: 30px;background-color:rgb(255, 216, 0)"><u><b>@ViewBag.Rapports</b></u></h5><br/>
        
        <br/>
        <div class="table-responsive">
            <div class="container mt-15">
                <div class="mt-3">


                    <table class="table table-striped table table-bordered" id="users-list">
                        <thead class="table-dark">
                            <tr>
                                <th>No</th>
                                <th>
                                    @Html.DisplayNameFor(model => model.vehicule.NumeroImatriculation)
                                </th>
                               
                                <th>
                                    @Html.DisplayNameFor(model => model.typeconsommation.NomTypeConsommation)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.quantite)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PrixUnitaire)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PrixTotal)
                                </th>
                                 <th>
                                    @Html.DisplayNameFor(model => model.DateConsommation)
                                </th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int no = 0;
                            }
                            @foreach (var item in Model)
                            {
                                no++;
                                <tr>
                                    <td>@no</td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.vehicule.NumeroImatriculation)
                                    </td>
                                    
                                    <td>
                                        @Html.DisplayFor(modelItem => item.typeconsommation.NomTypeConsommation)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.quantite)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PrixUnitaire)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PrixTotal)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DateConsommation)
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
@section scripts
{
    <script src="~/Scripts/Datatables.js"></script>
}

GestionConsommationVehiculeMvc/Views/Consommation/Index4.cshtml
@model IEnumerable<GestionConsommationVehiculeMvc.Models.consommation>
@{
    ViewBag.Title = "Index4";
    Layout = "~/Views/Layout/_Defaults.cshtml";
}
<!Doctype html>
<html lang="en">
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="background-color: rgb(0, 255, 255)">
        <h5 style="text-align: center; font-size: 30px; background-color: rgb(255, 216, 0)"><u><b>Rapport Detaille des consommations des vehicules</b></u></h5>
        <br />

        <b style="font-size: 27px; background-color: rgb(237, 17, 49)"><i class="fa fa-refresh fa-spin"></i><b style="text-align: center; color: black">@Html.ActionLink("Mettre a l'etat initial Cette affichage du rapport de la consommation des vehicules", "Index4")</b></b>
       <p>
            @using (Html.BeginForm("Index4", "Consommation", FormMethod.Post))
            {
                <span id="startDate"><b>DateDebut</b></span><input type="date" name="datedebut" />
                <span id="endDate"><b>DateFin</b></span><input type="date" name="datefin" />
                <input type="submit" name="submit" value="Rapport Detaille" />
            }
        </p>

        <h5 style="text-align: center; font-size: 30px; background-color: rgb(255, 216, 0)"><b><u>@ViewBag.Rapport</u></b></h5>
        <br />
       <br />
        <div class="table-responsive">
            <div class="container mt-15">
                <div class="mt-3">

                 <table class="table table-striped table table-bordered" id="users-list">
                        <thead class="table-dark">
                            <tr>
                                <th>No</th>
                                <th>
                                    @Html.DisplayNameFor(model => model.vehicule.NumeroImatriculation)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.typeconsommation.NomTypeConsommation)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.quantite)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PrixUnitaire)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PrixTotal)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DateConsommation)
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int no = 0;
                            }
                            @foreach (var item in Model)
                            {
                                no++;
                                <tr>
                                    <td>@no</td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.vehicule.NumeroImatriculation)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.typeconsommation.NomTypeConsommation)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.quantite)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PrixUnitaire)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PrixTotal)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DateConsommation)
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
@section scripts
{
    <script src="~/Scripts/Datatables.js"></script>
}